services:
  echo-service:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
      tags:
        - sfpscogs-scs.registry.snowflakecomputing.com/cube_testing/public/awesome_images/of:latest
    image: sfpscogs-scs.registry.snowflakecomputing.com/cube_testing/public/awesome_images/of:latest
    ports:
      - "8080:8080"
    environment:
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
      - SNOWFLAKE_ROLE=${SNOWFLAKE_ROLE}
      - SNOWFLAKE_USER=${SNOWFLAKE_USER}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      - SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE}
      - SNOWFLAKE_DATABASE=${SNOWFLAKE_DATABASE}
      - SNOWFLAKE_SCHEMA=${SNOWFLAKE_SCHEMA}
      - SNOWFLAKE_HOST=${SNOWFLAKE_HOST}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
