PUT file://tests/data/sp500_semantic_model.yaml @CUBE_TESTING.PUBLIC.ANALYST AUTO_COMPRESS = FALSE;
PUT file://tests/data/*.parquet @CUBE_TESTING.PUBLIC.DATA;

COPY INTO CUBE_TESTING.PUBLIC.SEC_CHUNK_SEARCH
FROM @CUBE_TESTING.PUBLIC.DATA/sec_chunk_search.parquet
FILE_FORMAT = (TYPE = PARQUET)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO CUBE_TESTING.PUBLIC.SP500
FROM @CUBE_TESTING.PUBLIC.DATA/sp500.parquet
FILE_FORMAT = (TYPE = PARQUET)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;